"""Run the #54 significance test: N permutations of the target-permutation null,
plus the secondary binomial hit-rate tests.

Resolves wayfinder ticket #54. Reads the fixed contract from
`kb/significance_spec.json` (`scripts/build_significance_spec.py`, committed
separately and first) and `prdict.significance`'s context/permutation logic.
Lighter-weight than #38/#39's harness — one homogeneous loop over a single
context (`xgboost`/`set2`/`final`), not a 12-context matrix — but the same
resumable-checkpoint idea: each completed permutation is written immediately,
fingerprinted against the current spec, so relaunching this script picks up
wherever it left off rather than re-running finished trials.

Output:
  runs/significance_checkpoint.parquet
      one row per completed permutation (seed, sharpe) -- the resume
      checkpoint. Not meant to be read by hand.
  runs/significance_test.log
      plain timestamped log, incrementally written.
  kb/significance_test.md
      the p-value, null distribution summary, and the secondary binomial
      hit-rate tests -- #54's actual deliverable.

Run via ./scripts/run_significance_test.sh, or directly:
    uv run python scripts/run_significance_test.py
"""

from __future__ import annotations

import hashlib
import json
import time
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

from prdict import encoding
from prdict.folds import load_fold_spec
from prdict.trading_calendar import load_calendar
from prdict.xgboost_model import load_xgboost_spec
from prdict.significance import (
    build_context,
    build_scoring_context,
    hit_rate_binomial_tests,
    load_significance_spec,
    run_permutation,
)

ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = ROOT / "runs"
CHECKPOINT_PATH = RUNS_DIR / "significance_checkpoint.parquet"
LOG_PATH = RUNS_DIR / "significance_test.log"
OUT_MD = ROOT / "kb" / "significance_test.md"


def _log(msg: str) -> None:
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    line = f"{datetime.now().strftime('%H:%M:%S')} {msg}"
    print(line)
    with LOG_PATH.open("a", buffering=1) as fh:
        fh.write(line + "\n")


def spec_fingerprint(sig_spec: dict) -> str:
    """Fingerprint over what actually determines a SINGLE permutation's result:
    target, null construction, model config, and the seed rule. Deliberately
    excludes `budget.n_permutations` — seeds are deterministic per-index
    (`seed_base + i`), so permutation i's result doesn't depend on how many
    total permutations are planned. Extending N later (to run more for tighter
    precision) must not invalidate already-completed permutations; only a
    change to what a permutation actually computes should.
    """
    fingerprint_fields = {
        "target": sig_spec["target"],
        "null_construction": sig_spec["null_construction"],
        "winning_params": sig_spec["winning_params"],
        "best_iteration": sig_spec["best_iteration"],
        "num_boost_round": sig_spec["num_boost_round"],
        "seed_base": sig_spec["budget"]["seed_base"],
        "seed_rule": sig_spec["budget"]["seed_rule"],
    }
    return hashlib.sha256(json.dumps(fingerprint_fields, sort_keys=True).encode()).hexdigest()[:16]


def _load_checkpoint(fingerprint: str) -> pd.DataFrame:
    """Completed (seed, sharpe) rows from a prior run under the SAME spec.
    A fingerprint mismatch (spec changed) is treated as nothing done."""
    if not CHECKPOINT_PATH.exists():
        return pd.DataFrame(columns=["seed", "sharpe", "spec_fingerprint"])
    df = pd.read_parquet(CHECKPOINT_PATH)
    return df[df["spec_fingerprint"] == fingerprint]


def _append_checkpoint(seed: int, sharpe: float, fingerprint: str) -> None:
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    row = pd.DataFrame([{"seed": seed, "sharpe": sharpe, "spec_fingerprint": fingerprint}])
    if CHECKPOINT_PATH.exists():
        existing = pd.read_parquet(CHECKPOINT_PATH)
        row = pd.concat([existing, row], ignore_index=True)
    row.to_parquet(CHECKPOINT_PATH)


def write_report(sig_spec: dict, null_sharpes: np.ndarray, binomial_rows: list[dict]) -> None:
    observed = sig_spec["target"]["observed_value"]
    n = len(null_sharpes)
    p_value = float((null_sharpes >= observed).mean())
    alpha = sig_spec["p_value"]["alpha"]

    lines = [
        "# Significance test result (#54)",
        "",
        "Generated by `scripts/run_significance_test.py`. Do not hand-edit — rerun the script.",
        "",
        f"Contract fixed in `kb/significance_spec.md`, written before any permutation ran. "
        f"Target: `{sig_spec['target']['model']}`/`{sig_spec['target']['set_name']}`/"
        f"`{sig_spec['target']['context']}` holdout Sharpe = **{observed}** "
        f"(#40's one flagged-but-unresolved result).",
        "",
        "## Primary: target-permutation null",
        "",
        f"**N = {n} permutations.** Null Sharpe: mean {null_sharpes.mean():+.4f}, "
        f"std {null_sharpes.std(ddof=1):.4f}, min {null_sharpes.min():+.4f}, "
        f"max {null_sharpes.max():+.4f}, 95th pct {np.percentile(null_sharpes, 95):+.4f}, "
        f"99th pct {np.percentile(null_sharpes, 99):+.4f}.",
        "",
        f"**Empirical p-value (one-sided, fraction of null Sharpes ≥ {observed}): {p_value:.4f}** "
        f"(alpha = {alpha}).",
        "",
        (
            f"**{'Significant' if p_value < alpha else 'Not significant'} at alpha={alpha}.** "
            + (
                "The observed holdout Sharpe is unusual even under a null where the astro "
                "features carry no relationship to future returns — real evidence the result "
                "isn't pure chance, though still one holdout window, not a replicated finding."
                if p_value < alpha
                else "A model trained on label-shuffled (noise) data reaches or beats the "
                "observed holdout Sharpe often enough that 0.426 is consistent with chance "
                "given the flexibility of the model class and the position-sizing mechanics — "
                "the honest read stays what #40 already said: one favorable window, not a "
                "discovered edge."
            )
        ),
        "",
        "## Secondary: binomial hit-rate tests",
        "",
        "Run at the **effective** sample size (`kb/fold_spec.md` §6: consecutive origins share "
        "9 of 10 label days, so overlapping daily calls are worth roughly 1/10th their raw count "
        "as independent observations — the raw count would make a real-but-small edge look far "
        "more significant than the data supports).",
        "",
        "| Model | Set | View | Hit rate | n (raw) | n (effective) | p-value |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in binomial_rows:
        lines.append(
            f"| {row['model']} | {row['set']} | {row['view']} | {row['hit_rate']:.3f} | "
            f"{row['n_calls_raw']} | {row['n_calls_effective']} | {row['p_value']:.4f} |"
        )
    lines.append("")
    OUT_MD.write_text("\n".join(lines) + "\n")
    _log(f"wrote {OUT_MD.relative_to(ROOT)}  p_value={p_value:.4f}")


def main() -> None:
    sig_spec = load_significance_spec()
    fingerprint = spec_fingerprint(sig_spec)
    n_total = sig_spec["budget"]["n_permutations"]
    seed_base = sig_spec["budget"]["seed_base"]
    seeds = [seed_base + i for i in range(n_total)]

    done = _load_checkpoint(fingerprint)
    done_seeds = set(done["seed"].tolist())
    remaining = [s for s in seeds if s not in done_seeds]

    _log(f"=== significance test: {n_total} permutations, {len(done_seeds)} already done, "
         f"{len(remaining)} remaining ===")

    cal = load_calendar()
    spec = encoding.load_spec()
    globals_ = encoding.load_global(spec)
    fs = load_fold_spec()
    xgb_spec = load_xgboost_spec()

    _log("building permutation context (fold-invariant set2 matrix, built once)...")
    ctx = build_context(cal, spec, globals_, fs)
    sc = build_scoring_context(cal)
    _log(f"context ready: fm_train {ctx.fm_train.values.shape}  fm_holdout {ctx.fm_holdout.values.shape}")

    start = time.monotonic()
    try:
        for i, seed in enumerate(remaining):
            t0 = time.monotonic()
            sharpe = run_permutation(ctx, xgb_spec["core"], sig_spec, sc, seed=seed)
            _append_checkpoint(seed, sharpe, fingerprint)
            elapsed = time.monotonic() - t0
            total_done = len(done_seeds) + i + 1
            _log(f"permutation {total_done}/{n_total}  seed={seed}  sharpe={sharpe:+.4f}  {elapsed:.1f}s")
    except KeyboardInterrupt:
        _log("=== interrupted — completed permutations are checkpointed, rerun to resume ===")

    final = _load_checkpoint(fingerprint)
    _log(f"=== {len(final)}/{n_total} permutations complete, {time.monotonic() - start:.1f}s this run ===")

    if len(final) == n_total:
        _log("computing secondary binomial hit-rate tests...")
        binomial_rows = hit_rate_binomial_tests(sc)
        write_report(sig_spec, final["sharpe"].to_numpy(), binomial_rows)
    else:
        _log(f"not all {n_total} permutations complete — rerun this script to finish, "
             f"report not written yet")


if __name__ == "__main__":
    main()
