"""Load the angular spec and apply the sin/cos transform.

The spec is generated by `scripts/build_angular_spec.py`; this module is the
read side, so no downstream stage decides a period for itself.

Two things here are load-bearing for later stages.

  * `transform()` **recomputes** every cross-planet separation from the
    longitudes. The file's `<a>_<b>_dist` columns are an unwrapped absolute
    difference, not an angle, and are discarded — see `kb/angular_spec.md`.
  * `pair_groups()` gives the `(sin, cos)` grouping that #12 and #13 must
    respect: a pair is kept or dropped as a unit, never split.

    uv run python -m prdict.angles    # self-check against nft50.csv
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "kb" / "angular_spec.json"
CSV_PATH = ROOT / "nft50.csv"

WEEKDAY_ORDER = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]


@dataclass(frozen=True)
class Transform:
    """One angular quantity: where its value comes from, and its circle."""

    source: str
    family: str
    stem: str
    value: str
    period: float
    origin: float
    replaces_source: bool
    emits: tuple[str, str]
    frm: str | None = None
    to: str | None = None

    def values(self, frame: pd.DataFrame) -> np.ndarray:
        """The quantity to place on the circle, in the source column's units."""
        if self.value == "column":
            return frame[self.source].to_numpy(dtype=float)
        if self.value == "signed_separation":
            lon_a = frame[f"{self.frm}_longitude"].to_numpy(dtype=float)
            lon_b = frame[f"{self.to}_longitude"].to_numpy(dtype=float)
            return (lon_b - lon_a) % 360.0
        if self.value == "weekday_index":
            index = {name: i for i, name in enumerate(WEEKDAY_ORDER)}
            mapped = frame[self.source].map(index)
            if mapped.isna().any():
                unknown = sorted(set(frame.loc[mapped.isna(), self.source]))
                raise ValueError(f"unknown weekday levels: {unknown}")
            return mapped.to_numpy(dtype=float)
        raise ValueError(f"unknown value rule {self.value!r} for {self.source}")

    def apply(self, frame: pd.DataFrame) -> pd.DataFrame:
        theta = 2.0 * np.pi * (self.values(frame) - self.origin) / self.period
        sin_name, cos_name = self.emits
        return pd.DataFrame(
            {sin_name: np.sin(theta), cos_name: np.cos(theta)}, index=frame.index
        )


@dataclass(frozen=True)
class AngularSpec:
    """Every angular transform, plus the columns dropped before transforming."""

    transforms: list[Transform]
    dropped_redundant: dict[str, str]
    emitted_columns: list[str]
    model_input_width: int

    @property
    def consumed(self) -> list[str]:
        """Source columns the transform replaces — dropped once it has run."""
        return [t.source for t in self.transforms if t.replaces_source]

    @property
    def discarded(self) -> list[str]:
        """Every angular column that does not survive: consumed or redundant."""
        return self.consumed + list(self.dropped_redundant)


def load_spec(path: Path = SPEC_PATH) -> AngularSpec:
    raw = json.loads(path.read_text())
    transforms = [
        Transform(
            source=t["source"],
            family=t["family"],
            stem=t["stem"],
            value=t["value"],
            period=float(t["period"]),
            origin=float(t["origin"]),
            replaces_source=bool(t["replaces_source"]),
            emits=(t["emits"][0], t["emits"][1]),
            frm=t.get("from"),
            to=t.get("to"),
        )
        for t in raw["transforms"]
    ]
    return AngularSpec(
        transforms=transforms,
        dropped_redundant=raw["dropped_redundant"],
        emitted_columns=[name for t in transforms for name in t.emits],
        model_input_width=raw["counts"]["model_input_width"],
    )


def pair_groups(spec: AngularSpec) -> dict[str, tuple[str, str]]:
    """Stem -> its (sin, cos) pair.

    Feature selection (#12) and PCA (#13) must treat each pair as one unit: a
    lone half is a wrong encoding of the angle, not a weaker one. `sin` alone
    identifies theta with 180 - theta, `cos` alone identifies theta with -theta.
    """
    return {t.stem: t.emits for t in spec.transforms}


def transform(frame: pd.DataFrame, spec: AngularSpec) -> pd.DataFrame:
    """Replace the angular columns with their sin/cos pairs.

    Raises if a source column the spec expects is absent, so a change to the
    source data fails here rather than silently emitting fewer features.
    """
    missing = [t.source for t in spec.transforms if t.source not in frame.columns]
    if missing:
        raise ValueError(
            f"frame is missing angular sources: {missing}. "
            "Rerun scripts/build_angular_spec.py if the source data changed."
        )

    emitted = pd.concat([t.apply(frame) for t in spec.transforms], axis=1)
    kept = frame.drop(columns=[c for c in spec.discarded if c in frame.columns])
    return pd.concat([kept, emitted], axis=1)


def main() -> None:
    from prdict import columns

    spec = load_spec()
    column_spec = columns.load_spec()
    frame = columns.apply_structural_fills(
        pd.read_csv(CSV_PATH, parse_dates=[column_spec.key]), column_spec
    )

    out = transform(frame, spec)
    print(f"{len(spec.transforms)} transforms -> {len(spec.emitted_columns)} columns")
    print(f"dropped as redundant : {len(spec.dropped_redundant)}")
    print(f"frame {frame.shape[1]} -> {out.shape[1]} columns")

    # Every emitted column must land on the unit circle, pairwise.
    for stem, (sin_name, cos_name) in pair_groups(spec).items():
        radius = np.hypot(out[sin_name], out[cos_name])
        assert np.allclose(radius, 1.0), f"{stem} is not on the unit circle"
    print(f"all {len(pair_groups(spec))} pairs lie on the unit circle")

    survivors = [
        c
        for c in out.columns
        if c not in {column_spec.key, column_spec.target_source, *column_spec.dropped}
    ]
    print(f"model input width    : {len(survivors)} (spec says {spec.model_input_width})")
    assert len(survivors) == spec.model_input_width

    nulls = int(out[spec.emitted_columns].isna().sum().sum())
    print(f"nulls in emitted     : {nulls}")
    assert nulls == 0


if __name__ == "__main__":
    main()
