"""Load the column spec and partition a raw frame by it.

The spec itself is generated by `scripts/build_column_spec.py`; this module is
the read side, used by every downstream stage so that no stage re-derives column
roles for itself.

    uv run python -m prdict.columns    # self-check against nft50.csv
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "kb" / "column_spec.json"
CSV_PATH = ROOT / "nft50.csv"


@dataclass(frozen=True)
class ColumnSpec:
    """Roles and types for every column of the source data."""

    key: str
    target_source: str
    dropped_price: list[str]
    dropped_constant: list[str]
    features: list[str]
    boolean: list[str]
    categorical: list[str]
    angular: list[str]
    linear_numeric: list[str]
    categorical_levels: dict[str, list[str]]
    structural_fill: dict[str, dict[str, str]]
    log1p_unsafe: list[str]
    n_columns: int
    label_cutoff: pd.Timestamp

    @property
    def numeric(self) -> list[str]:
        """Angular plus linear — the raw numeric columns of the source file.

        This is the *pre-transform* view. #7 has since landed: `angular` columns
        do not reach a model in this form — `prdict.angles.transform()` replaces
        them with sin/cos pairs, and drops eight of them outright as antipodal
        duplicates. A scaler or PCA should take its column list from the
        transformed frame, not from here.
        """
        return self.angular + self.linear_numeric

    @property
    def dropped(self) -> list[str]:
        return self.dropped_price + self.dropped_constant


def load_spec(path: Path = SPEC_PATH) -> ColumnSpec:
    raw = json.loads(path.read_text())
    roles, types = raw["roles"], raw["types"]
    return ColumnSpec(
        key=roles["key"][0],
        target_source=roles["target_source"][0],
        dropped_price=roles["dropped_price"],
        dropped_constant=roles["dropped_constant"],
        features=roles["feature"],
        boolean=types["boolean"],
        categorical=types["categorical"],
        angular=types["angular"],
        linear_numeric=types["linear_numeric"],
        categorical_levels=raw["categorical_levels"],
        structural_fill=raw["structural_fill"],
        log1p_unsafe=raw["log1p_unsafe"],
        n_columns=raw["source"]["n_columns"],
        label_cutoff=pd.Timestamp(raw["source"]["label_cutoff"]),
    )


def apply_structural_fills(frame: pd.DataFrame, spec: ColumnSpec) -> pd.DataFrame:
    """Fill the structurally-null columns with their sentinel level.

    Only `sun_vedha_target` qualifies today. The fill is not imputation — the
    sentinel is a declared level meaning "no vedha in effect".
    """
    filled = frame.copy()
    for col, rule in spec.structural_fill.items():
        filled[col] = filled[col].fillna(rule["value"])
    return filled


def partition(frame: pd.DataFrame, spec: ColumnSpec) -> dict[str, pd.DataFrame]:
    """Split a raw frame into role-keyed blocks, accounting for every column.

    Raises if the frame does not match the spec — a column added to or removed
    from the source data should fail loudly here rather than be silently dropped.
    """
    present, expected = set(frame.columns), set(
        [spec.key, spec.target_source, *spec.dropped, *spec.features]
    )
    if present != expected:
        missing, unexpected = sorted(expected - present), sorted(present - expected)
        raise ValueError(
            f"frame does not match spec — missing: {missing}, unexpected: {unexpected}. "
            "Rerun scripts/build_column_spec.py if the source data changed."
        )

    blocks = {
        "key": frame[[spec.key]],
        "target_source": frame[[spec.target_source]],
        "dropped": frame[spec.dropped],
        "boolean": frame[spec.boolean],
        "categorical": frame[spec.categorical],
        "angular": frame[spec.angular],
        "linear_numeric": frame[spec.linear_numeric],
    }

    accounted = sum(block.shape[1] for block in blocks.values())
    assert accounted == spec.n_columns, (
        f"partition covered {accounted} columns, expected {spec.n_columns}"
    )
    return blocks


def main() -> None:
    spec = load_spec()
    frame = pd.read_csv(CSV_PATH, parse_dates=[spec.key])
    blocks = partition(apply_structural_fills(frame, spec), spec)

    print(f"partitioned {frame.shape[1]} columns x {frame.shape[0]} rows")
    for name, block in blocks.items():
        print(f"  {name:16s}: {block.shape[1]:3d}")
    print(f"  {'TOTAL':16s}: {sum(b.shape[1] for b in blocks.values()):3d}")

    features = pd.concat(
        [blocks[k] for k in ("boolean", "categorical", "angular", "linear_numeric")],
        axis=1,
    )
    print(f"\nfeature nulls after structural fill: {int(features.isna().sum().sum())}")
    print(f"label cutoff: {spec.label_cutoff.date()}")


if __name__ == "__main__":
    main()
