"""Load the encoding spec and apply it, with the fit boundary enforced.

The spec is generated by `scripts/build_encoding_spec.py`; this module is the
read side, so no downstream stage decides a dtype or a fit scope for itself.

The load-bearing idea is that two fitted objects in this pipeline have opposite
lifetimes, and getting either one wrong leaks:

  * the categorical encoders are fitted on the **declared level list** and must
    be shared by every fold — refitting them per fold would size the embedding
    table from whatever that fold happened to observe, breaking map decision 6;
  * the scaler is fitted on **training-fold rows** and must never be shared —
    reusing one across folds leaks validation statistics into training.

So they are separated by construction rather than by convention. `load_global()`
has no parameter through which fold data could arrive; `build_fold()` cannot be
called without a training index, and what it returns refuses to pickle, so fold
state cannot be written to disk and reloaded somewhere it does not belong.
`assert_fit_boundary()` checks all of that and runs in the self-check.

    ./container/run.sh python -m prdict.encoding    # self-check against nft50.csv
"""

from __future__ import annotations

import hashlib
import inspect
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from prdict import angles, columns

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "kb" / "encoding_spec.json"
CATEGORIES_PATH = ROOT / "categories_list.json"
CSV_PATH = ROOT / "nft50.csv"

VIEWS = ("xgboost", "tft")


@dataclass(frozen=True)
class Family:
    """One column family and the contract that governs it."""

    name: str
    columns: list[str]
    fit_scope: str
    transform: str
    dtype: dict[str, str]
    tft_role: str

    @property
    def n(self) -> int:
        return len(self.columns)


@dataclass(frozen=True)
class EncodingSpec:
    """The per-family encoding contract. Semantics only — layout is #11."""

    families: list[Family]
    model_input_width: int
    sentinel_fills: dict[str, str]
    categories_sha256: str

    def family(self, name: str) -> Family:
        for f in self.families:
            if f.name == name:
                return f
        raise KeyError(f"no family {name!r}; have {[f.name for f in self.families]}")

    def scoped(self, scope: str) -> list[Family]:
        return [f for f in self.families if f.fit_scope == scope]

    def columns_in(self, scope: str) -> list[str]:
        return [c for f in self.scoped(scope) for c in f.columns]

    @property
    def all_columns(self) -> list[str]:
        return [c for f in self.families for c in f.columns]


def load_spec(path: Path = SPEC_PATH) -> EncodingSpec:
    """Read the spec, and refuse it if the declared level list has changed.

    The checksum is not ceremony: every global encoder in this pipeline is a
    pure function of `categories_list.json`, so if that file moves, every
    previously-computed code silently means something else.
    """
    raw = json.loads(path.read_text())
    recorded = raw["source"]["categories_list"]["sha256"]
    actual = hashlib.sha256(CATEGORIES_PATH.read_bytes()).hexdigest()
    if recorded != actual:
        raise ValueError(
            f"{CATEGORIES_PATH.name} has changed since the spec was built "
            f"(recorded {recorded[:12]}, found {actual[:12]}). It is given input "
            "and should not have. Rerun scripts/build_encoding_spec.py only if "
            "the change is intended."
        )
    return EncodingSpec(
        families=[
            Family(
                name=f["family"],
                columns=list(f["columns"]),
                fit_scope=f["fit_scope"],
                transform=f["transform"],
                dtype=dict(f["dtype"]),
                tft_role=f["tft_role"],
            )
            for f in raw["families"]
        ],
        model_input_width=raw["counts"]["model_input_width"],
        sentinel_fills=dict(raw["levels"]["sentinel_fills"]),
        categories_sha256=recorded,
    )


# --------------------------------------------------------------------------
# global scope — fitted on declared metadata, shared by every fold
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class GlobalEncoders:
    """Encoders derived from the declared level list alone.

    Deliberately **not** persisted. These are a pure function of a checked-in
    file, so rebuilding is cheaper than storing a pickle and cannot drift when
    `pytorch-forecasting` or `scikit-learn` changes its internals.
    """

    levels: dict[str, list[str]]

    def categorical_dtypes(self) -> dict[str, pd.CategoricalDtype]:
        """XGBoost view — declared categories, so codes are fold-invariant."""
        return {
            col: pd.CategoricalDtype(categories=levels, ordered=False)
            for col, levels in self.levels.items()
        }

    def label_encoders(self) -> dict[str, Any]:
        """TFT view — a `NaNLabelEncoder` per column, pre-fitted on declared levels.

        `add_nan=True` reserves index 0, so an unseen value at inference warns
        instead of raising. `TimeSeriesDataSet._preprocess_data` guards with
        `check_is_fitted` and will not refit these.
        """
        from pytorch_forecasting.data.encoders import NaNLabelEncoder

        encoders = {}
        for col, levels in self.levels.items():
            encoder = NaNLabelEncoder(add_nan=True)
            encoder.fit(pd.Series(levels, dtype=object))
            encoders[col] = encoder
        return encoders


def load_global(spec: EncodingSpec) -> GlobalEncoders:
    """Build the global encoders.

    There is no parameter here through which a training index, a fold, or a
    frame of observed data could be passed. That absence is the enforcement —
    `assert_fit_boundary()` fails if a data-bearing parameter is ever added.
    """
    cspec = columns.load_spec()
    categorical = spec.family("categorical").columns
    return GlobalEncoders(
        levels={col: list(cspec.categorical_levels[col]) for col in categorical}
    )


# --------------------------------------------------------------------------
# fold scope — fitted on training rows, must not outlive the fold
# --------------------------------------------------------------------------


class FoldState:
    """Transformers fitted on one fold's training rows.

    Refuses to pickle. Persisting fold state is how a scaler fitted on fold 3's
    training rows ends up scaling fold 4's validation rows; making that a type
    error is cheaper than catching it in review.
    """

    __slots__ = ("scaler", "columns", "n_train")

    def __init__(self, scaler: Any, columns_: list[str], n_train: int) -> None:
        self.scaler = scaler
        self.columns = columns_
        self.n_train = n_train

    def __reduce__(self):
        raise TypeError(
            "FoldState is not serializable by design — fold-fitted transformers "
            "must not outlive their fold. Refit with build_fold(spec, frame, "
            "train_idx) inside the fold that needs them."
        )

    def transform(self, frame: pd.DataFrame) -> pd.DataFrame:
        """Apply the fitted scaler to the fold-scoped columns of `frame`."""
        out = frame.copy()
        out[self.columns] = self.scaler.transform(frame[self.columns]).astype("float32")
        return out


def build_fold(spec: EncodingSpec, frame: pd.DataFrame, train_idx: Any) -> FoldState:
    """Fit the fold-scoped transformers on `train_idx` rows only.

    `train_idx` is required and positional — there is no default, so a fold's
    transformers cannot be built without naming the rows they may see.
    """
    from sklearn.preprocessing import StandardScaler

    cols = spec.columns_in("fold")
    train = frame.loc[train_idx, cols]
    if train.empty:
        raise ValueError("train_idx selected no rows — refusing to fit on nothing")

    scaler = StandardScaler().fit(train)
    return FoldState(scaler=scaler, columns_=cols, n_train=len(train))


# --------------------------------------------------------------------------
# dtype contract
# --------------------------------------------------------------------------


def apply_dtypes(
    frame: pd.DataFrame, spec: EncodingSpec, view: str, globals_: GlobalEncoders
) -> pd.DataFrame:
    """Cast every family to the dtype its view expects.

    This is the whole of #9's output: the same columns, typed per view. It does
    not decide column order, file format, or whether the result is one frame or
    two — #11 owns that.
    """
    if view not in VIEWS:
        raise ValueError(f"unknown view {view!r}; expected one of {VIEWS}")

    out = frame.copy()
    for family in spec.families:
        if family.name == "categorical":
            if view == "xgboost":
                for col, dtype in globals_.categorical_dtypes().items():
                    out[col] = out[col].astype(dtype)
            else:
                for col in family.columns:
                    out[col] = out[col].astype(str)
        elif family.name == "boolean":
            target = "int8" if view == "xgboost" else "float32"
            out[family.columns] = out[family.columns].astype(target)
        else:
            out[family.columns] = out[family.columns].astype("float32")
    return out


# --------------------------------------------------------------------------
# enforcement
# --------------------------------------------------------------------------


def assert_fit_boundary(spec: EncodingSpec) -> None:
    """Check the global/fold split structurally, not by reading comments."""
    # Exactly one fold-scoped family, and it is the unbounded-units one.
    fold_families = [f.name for f in spec.scoped("fold")]
    assert fold_families == ["linear_numeric"], (
        f"unexpected fold-scoped families: {fold_families}"
    )

    # No data-bearing parameter may reach the global builder.
    global_params = set(inspect.signature(load_global).parameters) - {"spec"}
    assert not global_params, (
        f"load_global() grew parameters {sorted(global_params)} — global encoders "
        "must not be able to see fold data"
    )

    # The fold builder must require its training index.
    fold_sig = inspect.signature(build_fold)
    train_param = fold_sig.parameters.get("train_idx")
    assert train_param is not None, "build_fold() lost its train_idx parameter"
    assert train_param.default is inspect.Parameter.empty, (
        "train_idx has a default — a fold could be fitted without naming its rows"
    )

    # Fold state must not be persistable.
    import pickle

    try:
        pickle.dumps(FoldState(scaler=None, columns_=[], n_train=0))
    except TypeError:
        pass
    else:
        raise AssertionError("FoldState pickled — fold state could outlive its fold")


def main() -> None:
    spec = load_spec()
    cspec = columns.load_spec()
    aspec = angles.load_spec()

    assert_fit_boundary(spec)
    print("fit boundary asserted")
    for scope in ("none", "global", "fold"):
        fams = spec.scoped(scope)
        names = ", ".join(f"{f.name}({f.n})" for f in fams) or "—"
        print(f"  {scope:6s}: {names}")

    frame = angles.transform(
        columns.apply_structural_fills(
            pd.read_csv(CSV_PATH, parse_dates=[cspec.key]), cspec
        ),
        aspec,
    )

    globals_ = load_global(spec)
    print(f"\nglobal encoders: {len(globals_.levels)} columns, rebuilt from declared levels")

    encoders = globals_.label_encoders()
    widths = {col: len(enc.classes_) for col, enc in encoders.items()}
    sample = "sun_vedha_target"
    print(
        f"  {sample}: {len(globals_.levels[sample])} declared -> "
        f"{widths[sample]} embedding rows (+1 reserved for NaN)"
    )
    assert all(widths[c] == len(globals_.levels[c]) + 1 for c in widths), (
        "an encoder sized itself from observed levels rather than declared ones"
    )

    # Both views carry the same columns; only dtypes differ.
    for view in VIEWS:
        typed = apply_dtypes(frame, spec, view, globals_)
        present = [c for c in spec.all_columns if c in typed.columns]
        assert len(present) == spec.model_input_width
        kinds = {f.name: str(typed[f.columns[0]].dtype) for f in spec.families}
        print(f"\n{view:8s} view: {len(present)} columns")
        for name, dtype in kinds.items():
            print(f"  {name:16s}: {dtype}")

    # A fold's scaler standardises training rows and leaves the rest alone.
    trainable = frame.index[: int(len(frame) * 0.6)]
    fold = build_fold(spec, frame, trainable)
    scaled = fold.transform(frame)
    train_block = scaled.loc[trainable, fold.columns].to_numpy(dtype=float)
    print(f"\nfold fit on {fold.n_train} rows, {len(fold.columns)} scaled columns")
    print(
        f"  train mean {np.nanmean(train_block):+.2e}  std {np.nanstd(train_block):.4f}"
    )
    assert abs(float(np.nanmean(train_block))) < 1e-6
    assert abs(float(np.nanstd(train_block)) - 1.0) < 1e-6

    untouched = spec.columns_in("none")
    assert scaled[untouched].equals(frame[untouched].astype(scaled[untouched].dtypes)), (
        "a scope-none column was modified by the fold scaler"
    )
    print(f"  {len(untouched)} scope-none columns untouched")


if __name__ == "__main__":
    main()
