"""Read the feature-independence spec — the base set and the per-model keep/drop.

The spec is generated by `scripts/build_independence_spec.py`; this module is the
read side, so no downstream stage re-derives which features are redundant or
decides for itself what a model may drop.

Resolves the read half of wayfinder ticket #15. The one thing #12 needs from here
is `drop_for(model)` / `keep_for(model)`: the sharp categorical boundaries are
redundant to a tree and dropped for XGBoost, kept as embeddings for the TFT
(`kb/independence_spec.md` for why). #12's stage-1 `|r| >= 0.95` prune runs on
what survives — it cannot find this redundancy itself, because a step function of
a continuous variable has almost no linear correlation with it.

    uv run python -m prdict.independence    # self-check against the spec
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "kb" / "independence_spec.json"

MODELS = ("xgboost", "tft")


@dataclass(frozen=True)
class Family:
    """One feature family and the decision recorded for it."""

    name: str
    columns: list[str]
    kind: str  # base | sharp_bin | smooth_bala | interaction
    determined_by: str | None
    rule: str | None
    keep: dict[str, bool]  # per model

    def kept_by(self, model: str) -> bool:
        return self.keep[model]


@dataclass(frozen=True)
class IndependenceSpec:
    """The base set, the dependency graph, and the per-model keep/drop policy."""

    families: list[Family]
    base_columns: list[str]
    redundant_base: list[str]  # base columns that are themselves determined
    policy: dict

    def family(self, name: str) -> Family:
        for f in self.families:
            if f.name == name:
                return f
        raise KeyError(f"no family {name!r}; have {[f.name for f in self.families]}")

    def keep_for(self, model: str) -> list[str]:
        """Feature columns that survive #15 for `model`, in spec order."""
        _check_model(model)
        redundant = set(self.redundant_base)
        return [
            c
            for f in self.families
            if f.kept_by(model)
            for c in f.columns
            if c not in redundant
        ]

    def drop_for(self, model: str) -> list[str]:
        """Feature columns #15 removes for `model` before selection even runs."""
        _check_model(model)
        keep = set(self.keep_for(model))
        return [c for f in self.families for c in f.columns if c not in keep]

    @property
    def deterministic_columns(self) -> list[str]:
        """Every column that is an exact function of the base set."""
        return [c for f in self.families if f.kind != "base" for c in f.columns]


def _check_model(model: str) -> None:
    if model not in MODELS:
        raise ValueError(f"unknown model {model!r}; expected one of {MODELS}")


def load_spec(path: Path = SPEC_PATH) -> IndependenceSpec:
    if not path.exists():
        raise FileNotFoundError(f"{path} does not exist. Run scripts/build_independence_spec.py first.")
    raw = json.loads(path.read_text())

    families = [
        Family(
            name=name,
            columns=list(g["columns"]),
            kind=g["kind"],
            determined_by=g["determined_by"],
            rule=g["rule"],
            keep=dict(g["keep"]),
        )
        for name, g in raw["families"].items()
    ]
    base_columns = [c for f in families if f.kind == "base" for c in f.columns]
    redundant = [raw["base_set"]["reductions"]["antipodal_longitude"]["column"]]
    return IndependenceSpec(
        families=families,
        base_columns=base_columns,
        redundant_base=redundant,
        policy=raw["policy"],
    )


def main() -> None:
    spec = load_spec()

    kinds: dict[str, int] = {}
    for f in spec.families:
        kinds[f.kind] = kinds.get(f.kind, 0) + len(f.columns)
    print("families by kind:", ", ".join(f"{k}={v}" for k, v in sorted(kinds.items())))
    print(f"base columns: {len(spec.base_columns)} "
          f"({len(spec.base_columns) - len(spec.redundant_base)} independent; "
          f"redundant: {spec.redundant_base})")
    print(f"deterministic dependents: {len(spec.deterministic_columns)}")

    for model in MODELS:
        keep, drop = spec.keep_for(model), spec.drop_for(model)
        recorded = spec.policy[model]["keep_n"]
        print(f"  {model:8s}: keep {len(keep)}, drop {len(drop)}  (spec records keep_n={recorded})")
        assert len(keep) == recorded, f"{model}: reader keep {len(keep)} != spec {recorded}"
        assert set(keep).isdisjoint(drop), f"{model}: a column is both kept and dropped"
        n_features = len(spec.deterministic_columns) + len(spec.base_columns)
        assert len(keep) + len(drop) == n_features, f"{model}: keep+drop != {n_features}"

    # The two models must agree on the base set and disagree only on sharp bins.
    only_xgb_drops = set(spec.drop_for("xgboost")) - set(spec.drop_for("tft"))
    sharp = {c for f in spec.families if f.kind == "sharp_bin" for c in f.columns}
    assert only_xgb_drops == sharp, "XGBoost/TFT should differ exactly on the sharp bins"
    print(f"XGBoost-only drops == the {len(sharp)} sharp-bin columns: verified")


if __name__ == "__main__":
    main()
