"""Read the set-1 selection artifact — the two-stage selected feature set.

The artifact is generated by `scripts/build_set1.py`; this module is the read
side, so no model stage re-runs the selection or reinterprets the fold-stability
rule. Set 1 is the correlation-pruned, target-ranked feature set (map decision 7);
set 2 (#13) is the PCA alternative. Both feed the scorecard.

The numeric part of set 1 is model-agnostic (rank/MI are scale-free). The
categorical part is **not** decided here — it follows #15's per-model policy
(`prdict.independence`): the TFT keeps the sharp bins as embeddings, XGBoost drops
them. `features_for(model)` composes the two.

    uv run python -m prdict.set1    # self-check against the artifact
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "kb" / "set1_spec.json"


@dataclass(frozen=True)
class Set1Spec:
    """The selected numeric features and the per-fold evidence behind them."""

    numeric_features: list[str]
    frequency: dict[str, dict]
    folds: list[dict]
    parameters: dict

    @property
    def majority(self) -> int:
        return self.parameters["fold_stability"]["threshold_folds"]

    @property
    def n_folds(self) -> int:
        return self.parameters["fold_stability"]["n_folds"]

    def selected_in(self, column: str) -> int:
        """How many folds selected this column (0 if it never entered the ranking)."""
        return self.frequency.get(column, {}).get("selected_folds", 0)

    def features_for(self, model: str) -> list[str]:
        """Set 1 for a model: its selected numeric features plus the kept categoricals.

        Only the **numeric** block is target-selected here; the categorical/boolean
        columns ride in per #15's structural policy (dropped for XGBoost, kept as
        embeddings for the TFT) rather than on weak target correlation. The same
        categoricals ride in set 2 unchanged — the two sets differ only in how the
        numeric block is treated (selection vs PCA, map decision 9). Kept separate
        from the numeric selection so a change to #15's policy does not silently
        move set 1's numeric definition, and vice versa.
        """
        from prdict import independence

        categorical = independence.load_spec().categorical_columns_for(model)
        return list(self.numeric_features) + categorical


def load_spec(path: Path = SPEC_PATH) -> Set1Spec:
    if not path.exists():
        raise FileNotFoundError(f"{path} does not exist. Run scripts/build_set1.py first.")
    raw = json.loads(path.read_text())
    return Set1Spec(
        numeric_features=list(raw["set1"]["numeric_features"]),
        frequency=dict(raw["frequency"]),
        folds=list(raw["folds"]),
        parameters=dict(raw["parameters"]),
    )


def main() -> None:
    spec = load_spec()

    print(f"set 1: {len(spec.numeric_features)} numeric features "
          f"(majority >= {spec.majority}/{spec.n_folds} folds)")
    for f in spec.folds:
        print(f"  fold {f['fold']}: survivors {f['survivors']:3d}  "
              f"null_p95 {f['null_mi_p95']:.5f}  selected {f['selected']}")

    # Every reported feature really cleared the majority.
    for c in spec.numeric_features:
        assert spec.selected_in(c) >= spec.majority, f"{c} in set1 but selected in {spec.selected_in(c)} folds"

    # Composition with #15 is consistent: the numeric part carries no categoricals,
    # and the TFT's set 1 is a superset of XGBoost's (it keeps the sharp bins).
    xgb = spec.features_for("xgboost")
    tft = spec.features_for("tft")
    assert set(xgb).issubset(tft), "XGBoost set 1 should be a subset of the TFT's"
    print(f"  features_for: xgboost {len(xgb)}, tft {len(tft)} "
          f"(+{len(tft) - len(xgb)} sharp-bin embeddings, per #15)")


if __name__ == "__main__":
    main()
