"""Read the set-2 spec, and fit the fold-scoped PCA it defines at train time.

The spec is generated by `scripts/build_set2_spec.py`; this module is the read
side plus the one thing that spec cannot freeze — the actual fitted PCA
loadings, which (like the fold-scoped scaler in #9/#11) must be refit inside
every fold rather than persisted. What the spec *does* freeze is the component
**count**: fixed once from fold 1 (`kb/set2_spec.md`), so every fold's PCA has
the same width even though its loadings differ.

Set 2 is independent of set 1 (#12) — a parallel PCA treatment of the same
`linear_numeric` block, not a rotation of set 1's selected survivors
(`CONTEXT.md`). The categorical/boolean part is not decided here — it follows
#15's per-model policy (`prdict.independence`), exactly as it does for set 1.

    uv run python -m prdict.set2    # self-check: refit fold 1, verify against the spec
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from prdict import encoding

ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "kb" / "set2_spec.json"

PCA_COLUMN_PREFIX = "pca_"


@dataclass(frozen=True)
class Set2Spec:
    """The fixed component count and the per-fold diagnostics behind it."""

    n_components: int
    target_variance: float
    blocks: list[dict]

    def pca_columns(self) -> list[str]:
        return [f"{PCA_COLUMN_PREFIX}{i}" for i in range(1, self.n_components + 1)]

    def explained_variance(self, fold: int | None) -> float:
        """The variance a given fold (or `None` for final_train) achieved at fit time."""
        for b in self.blocks:
            if (b["kind"] == "fold" and b["fold"] == fold) or (
                fold is None and b["kind"] == "final_train"
            ):
                return b["explained_variance"]
        raise KeyError(f"no recorded block for fold={fold!r}")


class PCAState:
    """A fold-fitted scaler + PCA, refusing to pickle — mirrors `encoding.FoldState`.

    Fitted once, inside one fold, on that fold's training rows only. Persisting it
    would let fold 3's PCA loadings score fold 4's validation rows; making that a
    type error is cheaper than catching it in review (the same reasoning #9 gives
    for `FoldState`).
    """

    __slots__ = ("_scaler_state", "_pca", "_linear_cols", "n_train")

    def __init__(self, scaler_state: Any, pca: Any, linear_cols: list[str], n_train: int) -> None:
        self._scaler_state = scaler_state
        self._pca = pca
        self._linear_cols = linear_cols
        self.n_train = n_train

    def __reduce__(self):
        raise TypeError(
            "PCAState is not serializable by design — fold-fitted PCA loadings must "
            "not outlive their fold. Refit with fit_fold(spec, frame, fold, cal) "
            "inside the fold that needs them."
        )

    def transform(self, frame: pd.DataFrame) -> pd.DataFrame:
        """Replace `linear_numeric` with `pca_1..pca_k`; every other column rides untouched."""
        scaled = self._scaler_state.transform(frame)
        components = self._pca.transform(scaled[self._linear_cols].to_numpy(dtype=float))
        out = scaled.drop(columns=self._linear_cols)
        cols = [f"{PCA_COLUMN_PREFIX}{i}" for i in range(1, components.shape[1] + 1)]
        out[cols] = components.astype(np.float32)
        return out


def load_spec(path: Path = SPEC_PATH) -> Set2Spec:
    if not path.exists():
        raise FileNotFoundError(f"{path} does not exist. Run scripts/build_set2_spec.py first.")
    raw = json.loads(path.read_text())
    return Set2Spec(
        n_components=raw["parameters"]["component_count"]["value"],
        target_variance=raw["parameters"]["component_count"]["target_variance"],
        blocks=raw["blocks"],
    )


def fit_fold(spec: encoding.EncodingSpec, frame: pd.DataFrame, fold: Any, cal: Any) -> PCAState:
    """Fit set 2's scaler + PCA on `fold`'s training rows, at the spec's fixed width.

    `fold` is duck-typed exactly like `dataset.fold_fit_rows` expects — anything
    with a `.train` `DatetimeIndex` (a walk-forward `Fold`, or a
    `SimpleNamespace(train=...)` for the final holdout refit).
    """
    from prdict.dataset import fold_fit_rows
    from sklearn.decomposition import PCA

    n_components = load_spec().n_components
    linear_cols = spec.family("linear_numeric").columns
    rows = fold_fit_rows(fold, cal)

    scaler_state = encoding.build_fold(spec, frame, rows)
    scaled = scaler_state.transform(frame)
    X_train = scaled.loc[rows, linear_cols].to_numpy(dtype=float)
    pca = PCA(n_components=n_components).fit(X_train)
    return PCAState(scaler_state, pca, linear_cols, n_train=len(rows))


def features_for(model: str) -> list[str]:
    """Set 2 for a model: the fixed PCA columns plus the kept categoricals.

    The PCA columns are model-agnostic (both consume the same components, #13
    item 5 — XGBoost's arm is a deliberate negative control, not an exclusion).
    Only the categorical/boolean part differs, via the same #15 policy set 1 uses.
    """
    from prdict import independence

    pca_cols = load_spec().pca_columns()
    categorical = independence.load_spec().categorical_columns_for(model)
    return pca_cols + categorical


def main() -> None:
    from prdict.folds import load_fold_spec
    from prdict.trading_calendar import load_calendar
    from prdict.dataset import encoded_features

    spec2 = load_spec()
    print(f"set 2: {spec2.n_components} components (fixed, target variance "
          f"{spec2.target_variance})")
    for b in spec2.blocks:
        label = f"fold {b['fold']}" if b["kind"] == "fold" else "final_train"
        print(f"  {label:12s}: {b['n_train_rows']} rows  variance {b['explained_variance']}")

    # Refit fold 1 fresh and confirm it reproduces the spec's own recorded numbers
    # — the spec is a snapshot of exactly this call, not a separate definition.
    cal = load_calendar()
    espec = encoding.load_spec()
    globals_ = encoding.load_global(espec)
    fs = load_fold_spec()
    fold1 = fs.folds(cal)[0]

    frame = encoded_features(cal, espec, globals_, "tft")
    state = fit_fold(espec, frame, fold1, cal)
    assert state.n_train == spec2.blocks[0]["n_train_rows"]

    transformed = state.transform(frame)
    pca_cols = spec2.pca_columns()
    assert all(c in transformed.columns for c in pca_cols)
    assert not any(c in transformed.columns for c in espec.family("linear_numeric").columns)
    assert all(c in transformed.columns for c in espec.family("cyclic").columns)
    print(f"\nrefit fold 1: {len(pca_cols)} pca columns present, "
          f"linear_numeric removed, cyclic untouched — matches the spec")

    from prdict import independence

    for model in ("xgboost", "tft"):
        feats = features_for(model)
        n_pca = sum(1 for c in feats if c.startswith(PCA_COLUMN_PREFIX))
        n_cat = len(independence.load_spec().categorical_columns_for(model))
        assert n_pca == spec2.n_components, f"{model}: {n_pca} pca cols, expected {spec2.n_components}"
        assert len(feats) == spec2.n_components + n_cat, f"{model}: composition mismatch"
        print(f"  features_for({model}): {len(feats)} ({n_pca} pca + {n_cat} categorical)")


if __name__ == "__main__":
    main()
