"""Load the trading-day calendar and place windows on it.

The calendar itself is generated by `scripts/build_trading_calendar.py`; this
module is the read side, so that no stage re-derives which dates are trading
days or where a window may start.

History comes from the data (`c` non-null). The forward block comes from a
frozen holiday list. Both are already resolved by the time this module loads
them — see `kb/trading_calendar.md` for why the rule is what it is.

    uv run python -m prdict.trading_calendar    # self-check against nft50.csv
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
CALENDAR_PATH = ROOT / "kb" / "trading_calendar.json"
CSV_PATH = ROOT / "nft50.csv"


@dataclass(frozen=True)
class TradingCalendar:
    """The trading-day index, and the window arithmetic that rides on it."""

    sessions: pd.DatetimeIndex
    n_history: int
    past: int
    future: int
    horizon: int

    @property
    def history(self) -> pd.DatetimeIndex:
        """Sessions with an observed close — the only ones that can carry a target."""
        return self.sessions[: self.n_history]

    @property
    def forward(self) -> pd.DatetimeIndex:
        """Sessions past the last observed close, where predictions live."""
        return self.sessions[self.n_history :]

    def position(self, day: pd.Timestamp | str) -> int:
        """Index of a session, raising if the date is not a trading day."""
        stamp = pd.Timestamp(day)
        loc = self.sessions.get_indexer([stamp])[0]
        if loc == -1:
            raise KeyError(f"{stamp.date()} is not a trading day")
        return int(loc)

    def is_session(self, day: pd.Timestamp | str) -> bool:
        return self.sessions.get_indexer([pd.Timestamp(day)])[0] != -1

    def origins(self, *, forward_steps: int | None = None) -> pd.DatetimeIndex:
        """Sessions usable as a window origin — the last day of the encoder block.

        An origin needs `past` sessions up to and including itself, and
        `forward_steps` sessions strictly after it. `forward_steps` defaults to
        the full known-covariate block; pass `horizon` instead to ask only for
        the sessions the target actually spans.
        """
        ahead = self.future if forward_steps is None else forward_steps
        return self.sessions[self.past - 1 : len(self.sessions) - ahead]

    def trainable_origins(self) -> pd.DatetimeIndex:
        """Origins whose whole target horizon has an observed close.

        The forward block has no target, so training stops `horizon` sessions
        before the last observed close.
        """
        return self.origins(forward_steps=self.horizon).intersection(
            self.history[: self.n_history - self.horizon]
        )

    def forward_origins(self) -> pd.DatetimeIndex:
        """Origins with no target — what forward inference actually runs over.

        Starts at the last observed close, whose forward returns are already
        unknown, and stops where the ephemeris runs out.
        """
        return self.origins()[self.origins().get_indexer([self.history[-1]])[0] :]

    def window(self, origin: pd.Timestamp | str) -> dict[str, pd.DatetimeIndex]:
        """The three date blocks of one window, in trading days."""
        i = self.position(origin)
        if i < self.past - 1:
            raise ValueError(f"{pd.Timestamp(origin).date()} has no full past-{self.past} block")
        if i + self.future >= len(self.sessions):
            raise ValueError(
                f"{pd.Timestamp(origin).date()} has no full future-{self.future} block "
                f"— the last such origin is {self.origins()[-1].date()}"
            )
        return {
            "past": self.sessions[i - self.past + 1 : i + 1],
            "future": self.sessions[i + 1 : i + 1 + self.future],
            "target": self.sessions[i + 1 : i + 1 + self.horizon],
        }


def load_calendar(path: Path = CALENDAR_PATH) -> TradingCalendar:
    raw = json.loads(path.read_text())
    frame = pd.read_csv(CSV_PATH, usecols=["record_date", "c"], parse_dates=["record_date"])
    frame = frame.sort_values("record_date")
    history = pd.DatetimeIndex(frame.loc[frame["c"].notna(), "record_date"])
    forward = pd.DatetimeIndex(raw["forward"]["sessions"])

    return TradingCalendar(
        sessions=history.append(forward),
        n_history=len(history),
        past=raw["index"]["past"],
        future=raw["index"]["future"],
        horizon=raw["index"]["horizon"],
    )


def restrict(frame: pd.DataFrame, cal: TradingCalendar, key: str = "record_date") -> pd.DataFrame:
    """Collapse a calendar-daily frame onto the trading-day index.

    Map decision 1: no forward-fill, no synthetic zero-return rows — non-trading
    days simply leave.
    """
    kept = frame[frame[key].isin(cal.sessions)].reset_index(drop=True)
    if len(kept) != len(cal.sessions):
        missing = cal.sessions.difference(pd.DatetimeIndex(kept[key]))
        raise ValueError(
            f"frame is missing {len(missing)} trading days, first {missing[0].date()}"
        )
    return kept


def main() -> None:
    cal = load_calendar()
    print(f"sessions       : {len(cal.sessions)}  "
          f"{cal.sessions[0].date()} → {cal.sessions[-1].date()}")
    print(f"  history      : {len(cal.history)}  ending {cal.history[-1].date()}")
    print(f"  forward      : {len(cal.forward)}  ending {cal.forward[-1].date()}")
    print(f"windows        : past {cal.past} / future {cal.future} / horizon {cal.horizon}")

    train, fwd = cal.trainable_origins(), cal.forward_origins()
    print(f"trainable origins: {len(train)}  {train[0].date()} → {train[-1].date()}")
    print(f"forward origins  : {len(fwd)}  {fwd[0].date()} → {fwd[-1].date()}")

    last = cal.window(fwd[-1])
    print(f"\nlast forward window, origin {fwd[-1].date()}")
    for name, block in last.items():
        print(f"  {name:7s}: {len(block):3d}  {block[0].date()} → {block[-1].date()}")

    frame = pd.read_csv(CSV_PATH, usecols=["record_date", "c"], parse_dates=["record_date"])
    print(f"\nrestrict(): {len(frame)} calendar rows → {len(restrict(frame, cal))} sessions")


if __name__ == "__main__":
    main()
